version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/connectors/athena-databricks-connector"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.junit.jupiter:*"
  - package-ecosystem: "maven"
    directory: "/connectors/athena-s3vector-connector"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.junit.jupiter:*"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"