name: Databricks Connector CI

on:
  pull_request:
    paths:
      - 'connectors/athena-databricks-connector/**'
  push:
    branches:
      - main
    paths:
      - 'connectors/athena-databricks-connector/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '11', '17' ]
    env:
      AWS_REGION: us-west-2
      AWS_DEFAULT_REGION: us-west-2
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: true
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java-version }}
      - name: Build with Maven
        run: mvn install -Dcheckstyle.skip=true
        working-directory: connectors/athena-databricks-connector
