name: Databricks Connector CI

on:
  pull_request:
    paths:
      - 'connectors/athena-databricks-connector/**'
  push:
    branches:
      - main
    paths:
      - 'connectors/athena-databricks-connector/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '11', '17' ]
    env:
      AWS_REGION: us-west-2
      AWS_DEFAULT_REGION: us-west-2
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java-version }}
      - name: Build with Maven
        run: mvn install -Dcheckstyle.skip=true
        working-directory: connectors/athena-databricks-connector
